sets = set()
sets.add(18)
sets.add(input("Enter your unique Numbers: "))
sets.add(input("Enter your unique Numbers: "))
sets.add(input("Enter your unique Numbers: "))
sets.add(input("Enter your unique Numbers: "))
sets.add(input("Enter your unique Numbers: "))
sets.add(input("Enter your unique Numbers: "))
sets.add(input("Enter your unique Numbers: "))
sets.add(input("Enter your unique Numbers: "))
print(sets)
